apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /home/oys/pvs/docker-registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-07-worker02

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  selector:
    app: docker-registry
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  selector:
    matchLabels:
      app: docker-registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - image: docker.io/registry:2.8.1
          name: docker-registry
          resources:
            limits:
              memory: 500Mi
              cpu: 200m
          ports:
            - containerPort: 5000
              name: docker-registry
          volumeMounts:
            - name: docker-registry
              mountPath: /var/lib/registry
      volumes:
        - name: docker-registry
          persistentVolumeClaim:
            claimName: docker-registry
